=== kirikprotocol/MSAG-Console/config/templates/InfoSme/informer.v3/conf/regions.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!ELEMENT regions (region*, region_default)>
<!ELEMENT region (mask*)>
<!ATTLIST region
	id CDATA #REQUIRED
	name CDATA #REQUIRED
        bandwidth CDATA #REQUIRED
        email CDATA #IMPLIED
        timezone CDATA #IMPLIED
        deleted CDATA #IMPLIED
        infosme_smsc CDATA ""
>
<!ELEMENT mask EMPTY>
<!ATTLIST mask
	value CDATA #REQUIRED
>

<!ELEMENT region_default EMPTY>
<!ATTLIST region_default
	bandwidth CDATA #REQUIRED
        email CDATA #IMPLIED
        timezone CDATA #IMPLIED
>

=== kirikprotocol/MSAG-Console/config/templates/InfoSme/informer.v3/conf/regions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE regions SYSTEM "regions.dtd">
<regions>
<region bandwidth="10" id="4" infosme_smsc="MSAG" name="Вся россия" timezone="21600,Asia/Novosibirsk">
<mask value="+7??????????"/>
</region>
<region bandwidth="100" deleted="true" id="2" infosme_smsc="Informer" name="МР Восток" timezone="21600,Asia/Novosibirsk">
<mask value="+7913000????"/>
<mask value="+7913001????"/>
<mask value="+7913???????"/>
</region>
<region bandwidth="200" deleted="true" id="3" infosme_smsc="Informer" name="МР Запад" timezone="10800,Europe/Moscow">
<mask value="+7916000????"/>
<mask value="+7916001????"/>
<mask value="+7916???????"/>
</region>
<region_default bandwidth="5"/>
</regions>
