=== kirikprotocol/MSAG-Console/config/resourcemanager/locale_resources.dtd
<?xml encoding="windows-1251"?>

<!ELEMENT locale_resources (settings*, resources*)>

<!ELEMENT settings (section*, param*)>
<!ELEMENT resources (section*, param*)>
<!ELEMENT section (section*, param*)>
<!ELEMENT param (#PCDATA)>

<!ATTLIST section  name CDATA #REQUIRED>
<!ATTLIST param    name CDATA #REQUIRED>

=== kirikprotocol/MSAG-Console/config/testing/resources/resources_en_us.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE locale_resources SYSTEM "file://locale_resources.dtd">

<locale_resources>
	<settings>
		<section name="delimiter">
			<param name="decimal">.</param>
			<param name="list">,</param>
		</section>
	</settings>
	<resources>
		<section name="profiler">
			<param name="msgDefault">Message character encoding is set to default encoding (now you are not able to receive messages with russian characters in the text even if your cell phone supports ucs2 messages)</param>
			<param name="msgUCS2">Message character encoding is set to ucs2 encoding (now you will be able to receive messages with russian characters in the case your cell phone supports ucs2 messages)</param>
			<param name="msgReportNone">Delivery reports are disabled</param>
			<param name="msgReportFull">Отчеты доставки разрешены</param>
			<param name="msgLocaleChanged">Locale is successfully changed</param>
			<param name="msgLocaleUnknown">Unknown locale</param>
			<param name="msgError">Неправильная команда (!@#$%^&*( )_+-=|\\:;'<,>.?/)</param>
		</section>
		<section name="abonentinfo">
			<param name="mobileFormat">Абонент $$string import="abonent"$$: статус $$string import="status"$$, msc $$string import="msc"$$</param>
			<param name="smeFormat">Abonent $$string import="abonent"$$: status $$int32 import="status"$$, encoding $$int32 import="encoding"$$, msc $$string import="msc"$$</param>
		</section>
		<section name="receipt">
			<section name="default">
				<param name="deliveredFormat" type="string">*Your message sent to $$string import="dest"$$ was successfully delivered on $$date pattern="dd MMMM yyyy, HH:mm:ss" import="date"$$</param>
				<param name="failedFormat" type="string">*Message to $$string import="dest"$$ sent on $$date pattern="dd MMMM yyyy, HH:mm:ss" import="date"$$ failed: $$string import="reason"$$. Resend the message to $$string import="dest"$$ once again and maybe you will have luck next time. Sincerely, smsc sme.</param>
				<param name="deletedFormat">#Сообщение на $$string import="dest"$$ от $$date pattern="dd-MM-yy HH:mm:ss" import="date"$$ удалено</param>
				<param name="notifyFormat" type="string">$Сообщение на $$string import="dest"$$ от $$date pattern="dd-MM-yy HH:mm:ss" import="date"$$ обломалось: $$string import="reason"$$</param>
			</section>
		</section>
		<section name="reason">
			<param name="0">No Error</param>
			<param name="1">Message Length is invalid</param>
			<param name="2">Command Length is invalid</param>
			<param name="3">Invalid Command ID</param>
			<param name="4">Incorrect BIND Status for given command</param>
			<param name="5">ESME Already in Bound State</param>
			<param name="6">Invalid Priority Flag</param>
			<param name="7">Invalid Registered Delivery Flag</param>
			<param name="8">System Error</param>
			<param name="10">Invalid Source Address</param>
			<param name="11">Invalid Dest Addr</param>
			<param name="12">Message ID is invalid</param>
			<param name="13">Bind Failed</param>
			<param name="14">Invalid Password</param>
			<param name="15">Invalid System ID</param>
			<param name="17">Cancel SM Failed</param>
			<param name="19">Replace SM Failed</param>
			<param name="20">Message Queue Full</param>
			<param name="21">Invalid Service Type</param>
			<param name="51">Invalid number of destinations</param>
			<param name="52">Invalid Distribution List name</param>
			<param name="64">Destination flag is invalid</param>
			<param name="66">Invalid 'submit with replace' request</param>
			<param name="67">Invalid esm_class field data</param>
			<param name="68">Cannot Submit to Distribution List</param>
			<param name="69">submit_sm or submit_multi failed</param>
			<param name="72">Invalid Source address TON</param>
			<param name="73">Invalid Source address NPI</param>
			<param name="80">Invalid Destination address TON</param>
			<param name="81">Invalid Destination address NPI</param>
			<param name="83">Invalid system_type field</param>
			<param name="84">Invalid replace_if_present flag</param>
			<param name="85">Invalid number of messages</param>
			<param name="88">Throttling error</param>
			<param name="97">Invalid Scheduled Delivery Time</param>
			<param name="98">Invalid message validity period</param>
			<param name="99">Predefined Message Invalid or Not Found</param>
			<param name="100">ESME Receiver Temporary App Error Code</param>
			<param name="101">ESME Receiver Permanent App Error Code</param>
			<param name="102">ESME Receiver Reject Message Error Code</param>
			<param name="103">query_sm request failed</param>
			<param name="192">Error in the optional part of the PDU Body</param>
			<param name="193">Optional Parameter not allowed</param>
			<param name="194">Invalid Parameter Length</param>
			<param name="195">Expected Optional Parameter missing</param>
			<param name="196">Invalid Optional Parameter Value</param>
			<param name="254">Delivery Failure</param>
			<param name="255">Unknown Error</param>
			<param name="260">Invalid Data Coding Scheme</param>

			<param name="1025">No route</param>
			<param name="1026">Message expired</param>
			<param name="1027">Delivery attempt timed out</param>
			<param name="1028">Sme is not connected</param>
			<param name="1029">Msc is blocked</param>

			<param name="1153">Unknown subscriber</param>
			<param name="1157">Unidentified subscriber</param>
			<param name="1161">Illegal subscriber</param>
			<param name="1164">Illegal Equipment</param>
			<param name="1165">Call Barred</param>
			<param name="1173">Facility Not Supported</param>
			<param name="1179">Absent Subscriber</param>
			<param name="1183">Subscriber Busy for MT SMS.</param>
			<param name="1184">SM Delivery Failure</param>
			<param name="1186">System Failure</param>
			<param name="1187">Data Missing</param>
			<param name="1188">Unexpected Data value</param>
		</section>
	</resources>
</locale_resources>

=== kirikprotocol/MSAG-Console/config/testing/resources/resources_ru_ru.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE locale_resources SYSTEM "file://locale_resources.dtd">

<locale_resources>
	<settings>
		<section name="delimiter">
			<param name="decimal">.</param>
			<param name="list">,</param>
		</section>
	</settings>
	<resources>
		<section name="profiler">
			<param name="msgDefault">Кодировка текста сообщений установлена в default (теперь вы не будете получать сообщения с русскими символами в тексте, даже если ваш телефон поддерживает ucs2 сообщения)</param>
			<param name="msgUCS2">Кодировка текста сообщений установлена в ucs2 (теперь вы сможете получать сообщения содержащие русские символы в тексте, однако ваш телефон должен поддерживать ucs2 сообщения)</param>
			<param name="msgLocaleChanged">Настройки locale успешно изменены</param>
			<param name="msgLocaleUnknown">Неправильно задан locale</param>
			<param name="msgHide">Включена hide опция</param>
			<param name="msgUnhide">Включена unhide опция</param>
			<param name="msgModificationDenied">У вас нет прав на изменение профиля</param>
			<param name="msgError"></param>
		</section>
		<section name="abonentinfo">
			<param name="smeFormat"></param>
		</section>
		<section name="receipt">
			<section name="default">
				<param name="deliveredFormat">*Сообщение на $$string import="dest"$$ доставлено $$date pattern="dd-MM-yy HH:mm:ss" import="date"$$</param>
				<param name="failedFormat">*Сообщение на $$string import="dest"$$ от $$date pattern="dd-MM-yy HH:mm:ss" import="date"$$ обломалось: $$string import="reason"$$. Пошлите сообщение на $$string import="dest"$$ еще раз и возможно вам повезет на этот раз. С уважением, smsc sme.</param>
				<param name="notifyFormat">$</param>
			</section>
			<section name="special">
				<param name="deliveredFormat">*=Сообщение на $$string import="dest"$$ доставлено $$date pattern="dd-MM-yy HH:mm:ss" import="date"$$</param>
				<param name="failedFormat">*=Сообщение на $$string import="dest"$$ от $$date pattern="dd-MM-yy HH:mm:ss" import="date"$$ обломалось: $$string import="reason"$$. Пошлите сообщение на $$string import="dest"$$ еще раз и возможно вам повезет на этот раз. С уважением, smsc sme.</param>
				<param name="notifyFormat">$=</param>
			</section>
		</section>
		<section name="reason">
			<param name="4">Неправильный тип соединения sme</param>
			<param name="20">Переполнение очереди</param>
			<param name="100">Временная ошибка</param>
			<param name="1026">Сообщение протухло</param>
			<param name="1027">Таймаут при доставке сообщения</param>
		</section>

		<section name="templates">
			<param name="t1">Привет $$string import="name" default="мир"$$</param>
			<param name="t2">Привет $$string import="name1" default="мир"$$ и $$string import="name2"$$ и все остальные. Перешлите это сообщение 10 своим друзьям. С приветом, мега темплейт.</param>
		</section>
	</resources>
</locale_resources>
