=== kirikprotocol/MSAG-Console/config/SmeRecords.dtd
<!ELEMENT records (smerecord*)>

<!ELEMENT smerecord (param+)>
<!ATTLIST smerecord 
    type (smpp|ss7) #REQUIRED 
    uid CDATA #REQUIRED>

<!ELEMENT param (#PCDATA)>
<!ATTLIST param 
    name (typeOfNumber|numberingPlan|interfaceVersion|systemType|password|addrRange|smeN|wantAlias|forceDC|timeout|priority|receiptSchemeName|disabled|mode) #REQUIRED 
    value CDATA #REQUIRED>

=== kirikprotocol/MSAG-Console/config/testing/admin/short/sme.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE records SYSTEM "file://SmeRecords.dtd">
<records>
<smerecord type="smpp" uid="MAP_PROXY">
	<param name="typeOfNumber" value="0"/>
	<param name="numberingPlan" value="0"/>
	<param name="interfaceVersion" value="52"/>
	<param name="systemType" value="2RnITsrGJV7d"/>
	<param name="password" value="S"/>
	<param name="addrRange" value=""/>
	<param name="smeN" value="-926875648"/>
	<param name="wantAlias" value="yes"/>
	<param name="timeout" value="22"/>
	<param name="priority" value="12007"/>
	<param name="disabled" value="false"/>
	<param name="mode" value="trx"/>
</smerecord>
<smerecord type="smpp" uid="DSTRLST">
	<param name="typeOfNumber" value="0"/>
	<param name="numberingPlan" value="0"/>
	<param name="interfaceVersion" value="52"/>
	<param name="systemType" value="2RnITsrGJV7d"/>
	<param name="password" value=""/>
	<param name="addrRange" value=""/>
	<param name="smeN" value="-926875648"/>
	<param name="wantAlias" value="yes"/>
	<param name="timeout" value="22"/>
	<param name="priority" value="12007"/>
	<param name="disabled" value="false"/>
	<param name="mode" value="trx"/>
</smerecord>
<smerecord type="smpp" uid="abonentinfo">
	<param name="typeOfNumber" value="0"/>
	<param name="numberingPlan" value="0"/>
	<param name="interfaceVersion" value="52"/>
	<param name="systemType" value="ftxDIsKifum2"/>
	<param name="password" value="fELb"/>
	<param name="addrRange" value=""/>
	<param name="smeN" value="-245170176"/>
	<param name="wantAlias" value="no"/>
	<param name="timeout" value="12"/>
	<param name="priority" value="4811"/>
	<param name="disabled" value="false"/>
	<param name="mode" value="trx"/>
</smerecord>
<smerecord type="smpp" uid="profiler">
	<param name="typeOfNumber" value="0"/>
	<param name="numberingPlan" value="0"/>
	<param name="interfaceVersion" value="52"/>
	<param name="systemType" value="TFlW7saGMNgN"/>
	<param name="password" value="zCFT3U5t"/>
	<param name="addrRange" value=""/>
	<param name="smeN" value="-360316928"/>
	<param name="wantAlias" value="no"/>
	<param name="timeout" value="22"/>
	<param name="priority" value="23595"/>
	<param name="disabled" value="false"/>
	<param name="mode" value="trx"/>
</smerecord>
<smerecord type="smpp" uid="smscsme">
	<param name="typeOfNumber" value="0"/>
	<param name="numberingPlan" value="0"/>
	<param name="interfaceVersion" value="52"/>
	<param name="systemType" value="aRyXOSrIHm3q"/>
	<param name="password" value="1Tb"/>
	<param name="addrRange" value=""/>
	<param name="smeN" value="-1263206400"/>
	<param name="wantAlias" value="no"/>
	<param name="timeout" value="16"/>
	<param name="priority" value="4609"/>
	<param name="disabled" value="false"/>
	<param name="mode" value="trx"/>
</smerecord>
<smerecord type="smpp" uid="wsme">
	<param name="typeOfNumber" value="0"/>
	<param name="numberingPlan" value="0"/>
	<param name="interfaceVersion" value="52"/>
	<param name="systemType" value=""/>
	<param name="password" value="wsme"/>
	<param name="addrRange" value=""/>
	<param name="smeN" value="-1263206400"/>
	<param name="wantAlias" value="yes"/>
	<param name="timeout" value="16"/>
	<param name="priority" value="4609"/>
	<param name="disabled" value="false"/>
	<param name="mode" value="trx"/>
</smerecord>
<smerecord type="smpp" uid="sme00">
	<param name="typeOfNumber" value="0"/>
	<param name="numberingPlan" value="0"/>
	<param name="interfaceVersion" value="52"/>
	<param name="systemType" value=""/>
	<param name="password" value=""/>
	<param name="addrRange" value=""/>
	<param name="smeN" value="0"/>
	<param name="wantAlias" value="yes"/>
	<param name="forceDC" value="false"/>
	<param name="timeout" value="10"/>
	<param name="priority" value="32"/>
	<param name="disabled" value="false"/>
	<param name="mode" value="rx"/>
</smerecord>
<smerecord type="smpp" uid="sme01">
	<param name="typeOfNumber" value="0"/>
	<param name="numberingPlan" value="0"/>
	<param name="interfaceVersion" value="52"/>
	<param name="systemType" value=""/>
	<param name="password" value=""/>
	<param name="addrRange" value=""/>
	<param name="smeN" value="0"/>
	<param name="wantAlias" value="yes"/>
	<param name="forceDC" value="false"/>
	<param name="timeout" value="10"/>
	<param name="priority" value="32"/>
	<param name="disabled" value="false"/>
	<param name="mode" value="tx"/>
</smerecord>
<smerecord type="smpp" uid="sme02">
	<param name="typeOfNumber" value="0"/>
	<param name="numberingPlan" value="0"/>
	<param name="interfaceVersion" value="52"/>
	<param name="systemType" value=""/>
	<param name="password" value=""/>
	<param name="addrRange" value=""/>
	<param name="smeN" value="0"/>
	<param name="wantAlias" value="yes"/>
	<param name="forceDC" value="false"/>
	<param name="timeout" value="10"/>
	<param name="priority" value="32"/>
	<param name="disabled" value="false"/>
	<param name="mode" value="trx"/>
</smerecord>
<smerecord type="smpp" uid="sme03">
	<param name="typeOfNumber" value="0"/>
	<param name="numberingPlan" value="0"/>
	<param name="interfaceVersion" value="52"/>
	<param name="systemType" value=""/>
	<param name="password" value=""/>
	<param name="addrRange" value=""/>
	<param name="smeN" value="0"/>
	<param name="wantAlias" value="yes"/>
	<param name="forceDC" value="false"/>
	<param name="timeout" value="10"/>
	<param name="priority" value="32"/>
	<param name="disabled" value="true"/>
	<param name="mode" value="rx"/>
</smerecord>
<smerecord type="smpp" uid="sme04">
	<param name="typeOfNumber" value="0"/>
	<param name="numberingPlan" value="0"/>
	<param name="interfaceVersion" value="52"/>
	<param name="systemType" value=""/>
	<param name="password" value=""/>
	<param name="addrRange" value=""/>
	<param name="smeN" value="0"/>
	<param name="wantAlias" value="yes"/>
	<param name="forceDC" value="false"/>
	<param name="timeout" value="10"/>
	<param name="priority" value="32"/>
	<param name="disabled" value="true"/>
	<param name="mode" value="tx"/>
</smerecord>
<smerecord type="smpp" uid="sme05">
	<param name="typeOfNumber" value="0"/>
	<param name="numberingPlan" value="0"/>
	<param name="interfaceVersion" value="52"/>
	<param name="systemType" value=""/>
	<param name="password" value=""/>
	<param name="addrRange" value=""/>
	<param name="smeN" value="0"/>
	<param name="wantAlias" value="yes"/>
	<param name="forceDC" value="false"/>
	<param name="timeout" value="10"/>
	<param name="priority" value="32"/>
	<param name="disabled" value="true"/>
	<param name="mode" value="trx"/>
</smerecord>
</records>

=== kirikprotocol/MSAG-Console/config/testing/submit_multi/sme.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE records SYSTEM "SmeRecords.dtd">
<records>
<smerecord type="smpp" uid="sme0">
	<param name="typeOfNumber" value="1"/>
	<param name="numberingPlan" value="1"/>
	<param name="interfaceVersion" value="52"/>
	<param name="systemType" value="aaa"/>
	<param name="password" value="sme0"/>
	<param name="addrRange" value=""/>
	<param name="smeN" value="123"/>
	<param name="wantAlias" value="yes"/>
	<param name="forceDC" value="false"/>
	<param name="timeout" value="10"/>
	<param name="priority" value="12345"/>
	<param name="receiptSchemeName" value="default"/>
</smerecord>
<smerecord type="smpp" uid="sme1">
	<param name="typeOfNumber" value="1"/>
	<param name="numberingPlan" value="1"/>
	<param name="interfaceVersion" value="52"/>
	<param name="systemType" value="aaa"/>
	<param name="password" value="sme1"/>
	<param name="addrRange" value=""/>
	<param name="smeN" value="123"/>
	<param name="wantAlias" value="yes"/>
	<param name="forceDC" value="false"/>
	<param name="timeout" value="10"/>
	<param name="priority" value="12345"/>
	<param name="receiptSchemeName" value="default"/>
</smerecord>
<smerecord type="smpp" uid="sme2">
	<param name="typeOfNumber" value="1"/>
	<param name="numberingPlan" value="1"/>
	<param name="interfaceVersion" value="52"/>
	<param name="systemType" value="aaa"/>
	<param name="password" value="sme2"/>
	<param name="addrRange" value=""/>
	<param name="smeN" value="123"/>
	<param name="wantAlias" value="yes"/>
	<param name="forceDC" value="false"/>
	<param name="timeout" value="10"/>
	<param name="priority" value="12345"/>
	<param name="receiptSchemeName" value="default"/>
</smerecord>
<smerecord type="smpp" uid="sme3">
	<param name="typeOfNumber" value="1"/>
	<param name="numberingPlan" value="1"/>
	<param name="interfaceVersion" value="52"/>
	<param name="systemType" value="aaa"/>
	<param name="password" value="sme3"/>
	<param name="addrRange" value=""/>
	<param name="smeN" value="123"/>
	<param name="wantAlias" value="yes"/>
	<param name="forceDC" value="false"/>
	<param name="timeout" value="10"/>
	<param name="priority" value="12345"/>
	<param name="receiptSchemeName" value="default"/>
</smerecord>
<smerecord type="smpp" uid="sme4">
	<param name="typeOfNumber" value="1"/>
	<param name="numberingPlan" value="1"/>
	<param name="interfaceVersion" value="52"/>
	<param name="systemType" value="aaa"/>
	<param name="password" value="sme4"/>
	<param name="addrRange" value=""/>
	<param name="smeN" value="123"/>
	<param name="wantAlias" value="yes"/>
	<param name="forceDC" value="false"/>
	<param name="timeout" value="10"/>
	<param name="priority" value="12345"/>
	<param name="receiptSchemeName" value="default"/>
</smerecord>
<smerecord type="smpp" uid="MAP_PROXY">
	<param name="typeOfNumber" value="1"/>
	<param name="numberingPlan" value="1"/>
	<param name="interfaceVersion" value="52"/>
	<param name="systemType" value="aaa"/>
	<param name="password" value="sme5"/>
	<param name="addrRange" value=""/>
	<param name="smeN" value="123"/>
	<param name="wantAlias" value="yes"/>
	<param name="forceDC" value="false"/>
	<param name="timeout" value="10"/>
	<param name="priority" value="12345"/>
	<param name="receiptSchemeName" value="default"/>
</smerecord>

<smerecord type="smpp" uid="DSTRLST">
	<param name="typeOfNumber" value="0"/>
	<param name="numberingPlan" value="0"/>
	<param name="interfaceVersion" value="52"/>
	<param name="systemType" value="1R2eF968bFv7"/>
	<param name="password" value="12l"/>
	<param name="addrRange" value=""/>
	<param name="smeN" value="-328269824"/>
	<param name="wantAlias" value="no"/>
	<param name="forceDC" value="true"/>
	<param name="timeout" value="18"/>
	<param name="priority" value="9674"/>
	<param name="receiptSchemeName" value="default"/>
</smerecord>
<smerecord type="smpp" uid="abonentinfo">
	<param name="typeOfNumber" value="0"/>
	<param name="numberingPlan" value="0"/>
	<param name="interfaceVersion" value="52"/>
	<param name="systemType" value="40u573u9f337"/>
	<param name="password" value="k22v3"/>
	<param name="addrRange" value=""/>
	<param name="smeN" value="-520159232"/>
	<param name="wantAlias" value="no"/>
	<param name="forceDC" value="true"/>
	<param name="timeout" value="25"/>
	<param name="priority" value="17782"/>
	<param name="receiptSchemeName" value="default"/>
</smerecord>
<smerecord type="smpp" uid="profiler">
	<param name="typeOfNumber" value="0"/>
	<param name="numberingPlan" value="0"/>
	<param name="interfaceVersion" value="52"/>
	<param name="systemType" value="15fPam74Sd26"/>
	<param name="password" value="O"/>
	<param name="addrRange" value=""/>
	<param name="smeN" value="-1135345664"/>
	<param name="wantAlias" value="no"/>
	<param name="forceDC" value="true"/>
	<param name="timeout" value="8"/>
	<param name="priority" value="11299"/>
	<param name="receiptSchemeName" value="default"/>
</smerecord>
<smerecord type="smpp" uid="smscsme">
	<param name="typeOfNumber" value="0"/>
	<param name="numberingPlan" value="0"/>
	<param name="interfaceVersion" value="52"/>
	<param name="systemType" value="27Ij4Ri9q0bh"/>
	<param name="password" value="0"/>
	<param name="addrRange" value=""/>
	<param name="smeN" value="-779616256"/>
	<param name="wantAlias" value="yes"/>
	<param name="forceDC" value="true"/>
	<param name="timeout" value="17"/>
	<param name="priority" value="23519"/>
	<param name="receiptSchemeName" value="special"/>
</smerecord>
</records>

=== kirikprotocol/MSAG-Console/config/templates/smsc/sme.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE records SYSTEM "file://SmeRecords.dtd">

<records>
<smerecord type="smpp" uid="profiler">
  <param name="typeOfNumber" value="1"/>
  <param name="numberingPlan" value="1"/>
  <param name="interfaceVersion" value="34"/>
  <param name="systemType" value="internal"/>
  <param name="password" value=""/>
  <param name="addrRange" value=".*"/>
  <param name="smeN" value="-1"/>
  <param name="wantAlias" value="no"/>
  <param name="forceDC" value="false"/>
  <param name="timeout" value="20"/>
  <param name="receiptSchemeName" value="default"/>
  <param name="priority" value="16384"/>
  <param name="disabled" value="false"/>
  <param name="mode" value="trx"/>
  <param name="proclimit" value="0"/>
  <param name="schedlimit" value="0"/>
  <param name="accessMask" value="1"/>  
</smerecord>
<smerecord type="smpp" uid="NULLSME">
  <param name="typeOfNumber" value="1"/>
  <param name="numberingPlan" value="1"/>
  <param name="interfaceVersion" value="34"/>
  <param name="systemType" value="internal"/>
  <param name="password" value=""/>
  <param name="addrRange" value=""/>
  <param name="smeN" value="-1"/>
  <param name="wantAlias" value="no"/>
  <param name="forceDC" value="false"/>
  <param name="timeout" value="20"/>
  <param name="receiptSchemeName" value="default"/>
  <param name="priority" value="16384"/>
  <param name="disabled" value="false"/>
  <param name="mode" value="trx"/>
  <param name="proclimit" value="0"/>
  <param name="schedlimit" value="0"/>
  <param name="accessMask" value="1"/>  
</smerecord>
<smerecord type="smpp" uid="abonentinfo">
  <param name="typeOfNumber" value="1"/>
  <param name="numberingPlan" value="1"/>
  <param name="interfaceVersion" value="34"/>
  <param name="systemType" value="internal"/>
  <param name="password" value=""/>
  <param name="addrRange" value=".*"/>
  <param name="smeN" value="-1"/>
  <param name="wantAlias" value="no"/>
  <param name="forceDC" value="false"/>
  <param name="timeout" value="20"/>
  <param name="receiptSchemeName" value="default"/>
  <param name="priority" value="16384"/>
  <param name="disabled" value="false"/>
  <param name="mode" value="trx"/>
  <param name="proclimit" value="0"/>
  <param name="schedlimit" value="0"/>
  <param name="accessMask" value="1"/>  
</smerecord>
<smerecord type="smpp" uid="MAP_PROXY">
  <param name="typeOfNumber" value="1"/>
  <param name="numberingPlan" value="1"/>
  <param name="interfaceVersion" value="34"/>
  <param name="systemType" value="internal"/>
  <param name="password" value=""/>
  <param name="addrRange" value=".*"/>
  <param name="smeN" value="-1"/>
  <param name="wantAlias" value="no"/>
  <param name="forceDC" value="false"/>
  <param name="timeout" value="20"/>
  <param name="receiptSchemeName" value="default"/>
  <param name="priority" value="16384"/>
  <param name="disabled" value="false"/>
  <param name="mode" value="trx"/>
  <param name="proclimit" value="5000"/>
  <param name="schedlimit" value="0"/>
  <param name="accessMask" value="1"/>  
</smerecord>
<smerecord type="smpp" uid="smscsme">
  <param name="typeOfNumber" value="1"/>
  <param name="numberingPlan" value="1"/>
  <param name="interfaceVersion" value="52"/>
  <param name="systemType" value="internal"/>
  <param name="password" value=""/>
  <param name="addrRange" value=".*"/>
  <param name="smeN" value="-1"/>
  <param name="wantAlias" value="no"/>
  <param name="forceDC" value="false"/>
  <param name="timeout" value="20"/>
  <param name="receiptSchemeName" value="default"/>
  <param name="priority" value="16384"/>
  <param name="disabled" value="false"/>
  <param name="mode" value="trx"/>
  <param name="proclimit" value="0"/>
  <param name="schedlimit" value="0"/>
  <param name="accessMask" value="1"/>  
</smerecord>
<smerecord type="smpp" uid="scheduler">
  <param name="typeOfNumber" value="1"/>
  <param name="numberingPlan" value="1"/>
  <param name="interfaceVersion" value="34"/>
  <param name="systemType" value="internal"/>
  <param name="password" value=""/>
  <param name="addrRange" value=""/>
  <param name="smeN" value="-1"/>
  <param name="wantAlias" value="no"/>
  <param name="forceDC" value="false"/>
  <param name="timeout" value="20"/>
  <param name="receiptSchemeName" value="default"/>
  <param name="priority" value="16384"/>
  <param name="disabled" value="false"/>
  <param name="mode" value="trx"/>
  <param name="proclimit" value="0"/>
  <param name="schedlimit" value="0"/>
  <param name="accessMask" value="1"/>  
</smerecord>
<smerecord type="smpp" uid="DSTRLST">
  <param name="typeOfNumber" value="1"/>
  <param name="numberingPlan" value="1"/>
  <param name="interfaceVersion" value="34"/>
  <param name="systemType" value="internal"/>
  <param name="password" value=""/>
  <param name="addrRange" value=".*"/>
  <param name="smeN" value="-1"/>
  <param name="wantAlias" value="no"/>
  <param name="forceDC" value="false"/>
  <param name="timeout" value="20"/>
  <param name="receiptSchemeName" value="default"/>
  <param name="priority" value="16384"/>
  <param name="disabled" value="false"/>
  <param name="mode" value="trx"/>
  <param name="proclimit" value="0"/>
  <param name="schedlimit" value="0"/>
  <param name="accessMask" value="1"/>  
</smerecord>
<smerecord type="smpp" uid="INMANCOMM">
  <param name="typeOfNumber" value="1"/>
  <param name="numberingPlan" value="1"/>
  <param name="interfaceVersion" value="34"/>
  <param name="systemType" value="internal"/>
  <param name="password" value=""/>
  <param name="addrRange" value=".*"/>
  <param name="smeN" value="-1"/>
  <param name="wantAlias" value="no"/>
  <param name="forceDC" value="false"/>
  <param name="timeout" value="20"/>
  <param name="receiptSchemeName" value="default"/>
  <param name="priority" value="16384"/>
  <param name="disabled" value="false"/>
  <param name="mode" value="trx"/>
  <param name="proclimit" value="0"/>
  <param name="schedlimit" value="0"/>
  <param name="accessMask" value="1"/>  
</smerecord>
</records>
