=== kirikprotocol/MSAG-Console/config/snmp.dtd
<!ELEMENT config (counterInterval,default,object*) >
<!ELEMENT counterInterval EMPTY>
<!ATTLIST counterInterval value CDATA #REQUIRED>
<!ELEMENT default (counter*)>
<!ELEMENT counter (#PCDATA)>
<!ATTLIST counter name CDATA #REQUIRED>
<!ELEMENT object (counter*)>
<!ATTLIST object id CDATA #REQUIRED enabled (true|false) #REQUIRED>

=== kirikprotocol/MSAG-Console/config/templates/smsc/snmp.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE config SYSTEM "snmp.dtd">
<config>
  <counterInterval value="300"/>
  <default>
    <counter name="accepted">50,40,30,20</counter>
    <counter name="rejected">10,20,30,40</counter>
    <counter name="retried">10,20,30,40</counter>
    <counter name="delivered">50,40,30,20</counter>
    <counter name="failed">10,20,30,40</counter>
    <counter name="temperror">10,20,30,40</counter>
    <counter name="0x014">10,20,30,40</counter>
    <counter name="0x058">10,20,30,40</counter>
    <counter name="0x00d">10,20,30,40</counter>
    <counter name="SDP">10,20,30,40</counter>
    <counter name="other">10,20,30,40</counter>
  </default>
  <object id="GLOBAL" enabled="true">
    <counter name="accepted">0,0,0,0</counter>
  </object>
</config>
