=== kirikprotocol/MSAG-Console/config/scag/counters.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ELEMENT counters (param|templates|ca_tables)*>
<!ELEMENT param (#PCDATA)>
<!ATTLIST param
    name CDATA #REQUIRED
    type (string|int|bool) #IMPLIED>

<!ELEMENT templates (template)*>
<!ELEMENT template (name|ca|param*)>
<!ATTLIST template
    id CDATA #REQUIRED
    type (ACCUMULATOR|INTEGRAL|AVERAGE|HISTOGRAMM) #REQUIRED>
<!ELEMENT ca>
<!ATTLIST ca
    id CDATA #REQUIRED>

<!ELEMENT ca_tables (ca_table)*>
<!ELEMENT ca_table (name|limits|param*)>
<!ATTLIST ca_table
    id CDATA #REQUIRED
    system (true|false) "false">
<!ELEMENT limits (limit)*>
<!ATTLIST limits
    min CDATA #IMPLIED
    max CDATA #REQUIRED>
<!ELEMENT limit>
<!ATTLIST limit
    procent CDATA #REQUIRED
    severity (NORMAL|WARNING|MINOR|MAJOR|CRITICAL) #REQUIRED>

<!ELEMENT name (#PCDATA)>

=== kirikprotocol/MSAG-Console/config/templates/pvss/counters.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE counters SYSTEM "counters.dtd">

<counters>
    <ca_tables>
        <ca_table id="sys.profiles.abn.total" system="true">
            <limits min="0" max="100">
	    </limits>
        </ca_table>

    </ca_tables>
    
    <templates>
        <template id="SimpleAcc" type="ACCUMULATOR">
	    <ca id="user.defaultTable"/>
	</template>
        <template id="SimpleAvg" type="AVERAGE">
            <ca id="user.table1"/>
            <param name="nseconds" type="int">10</param>
	</template>
	<template id="SimpleIntegral" type="INTEGRAL">
	    <ca id="user.defaultTable"/>
            <param name="nseconds" type="int">10</param>
            <param name="msecresol" type="int">100</param>
	</template>
    </templates>

</counters>
