=== kirikprotocol/MSAG-Console/config/scag/http_routes.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ELEMENT routes (subject_def*, route*)>
<!ELEMENT route ((address|subject)*, url)>
<!ATTLIST route
    id CDATA #REQUIRED
    serviceId CDATA #REQUIRED
>
<!ELEMENT address EMPTY>
<!ATTLIST address
    value CDATA #REQUIRED
>
<!ELEMENT url EMPTY>
<!ATTLIST url
    value CDATA #REQUIRED
>

<!ELEMENT subject EMPTY>
<!ATTLIST subject
    id CDATA #REQUIRED
>

<!ELEMENT subject_def (address+)>
<!ATTLIST id
    value CDATA #REQUIRED
>

=== kirikprotocol/MSAG-Console/config/templates/scag/http_routes.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE http_routes SYSTEM "http_routes.dtd">
<routes>
    <subject_def id="MTS_numbers">        <address value="+7902912????"/>
        <address value="+7905985????"/>
    </subject_def>

    <route id="route1" serviceId="5">        <subject id="MTS_numbers"/>        <address value="+7913???????"/>        <address value="+7903???????"/>        <url value="yandex.ru"/>    </route>
    <route id="route2" serviceId="6">
        <address value="+7912???????"/>
        <address value="+7906???????"/>
        <url value="yandex.ru"/>
    </route>

</routes>
