=== kirikprotocol/MSAG-Console/webapps/smsc/WEB-INF/classes/dtds/users.dtd
<!ELEMENT users (user+)>

<!ELEMENT user (role+)>
<!ATTLIST user
	login CDATA #REQUIRED
	password CDATA #REQUIRED
	firstName CDATA #IMPLIED
	lastName CDATA #IMPLIED
	dept CDATA #IMPLIED
	workPhone CDATA #IMPLIED
	homePhone CDATA #IMPLIED
	cellPhone CDATA #IMPLIED
	email CDATA #IMPLIED
>

<!ELEMENT role EMPTY>
<!ATTLIST role
	name CDATA #REQUIRED
>

=== kirikprotocol/MSAG-Console/webapps/smsc/WEB-INF/users.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE config SYSTEM "file://users.dtd">

<users>
	<user name="superadmin" password="123">
		<role name="user"/>
		<role name="admin"/>
		<role name="super-admin"/>
	</user>
	<user name="admin" password="123">
		<role name="user"/>
		<role name="admin"/>
	</user>
	<user name="user1" password="123">
		<role name="user"/>
	</user>
	<user name="user2" password="456">
		<role name="user"/>
	</user>
	<user name="user3" password="789">
		<role name="user"/>
	</user>
</users>
