=== kirikprotocol/MSAG-Console/config/templates/MCIProf/schema/scenarios.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT scenarios (scenario+)>

<!--
USSD:
  0 - not supported
  1 - USSD phase 1
  2 - USSD phase 2

SMS:
  0 - not supported
  1 - dialog via SMS
  2 - initialize USSD dialog (WARNING! In this case "ussd" value should be 2.)
-->
<!ELEMENT scenario (scenarioPreProcessor?,scenarioPostProcesoor?,errorHandler?,page+)>
<!ATTLIST scenario id            CDATA #REQUIRED
                   active        (0|1|yes|no|true|false|YES|NO|TRUE|FALSE) "0"
                   ussd          (0|1|2) "2"
                   sms           (0|1|2) "2"
                   resources     CDATA #IMPLIED>

<!ELEMENT page (pagePreProcessor?,pagePostProcessor?,(pageExecutor|segment+),command*)>
<!ATTLIST page id            CDATA #REQUIRED
               question      CDATA #REQUIRED
               shortcut      CDATA #IMPLIED>

<!ELEMENT segment (data|segmentExecutor)>

<!ELEMENT data (#PCDATA)>

<!ELEMENT command EMPTY>
<!ATTLIST command name    CDATA #REQUIRED
                  target  CDATA #REQUIRED>

<!ELEMENT scenarioPreProcessor (initParam|bundle)*>
<!ATTLIST scenarioPreProcessor class CDATA #REQUIRED>

<!ELEMENT scenarioPostProcessor (initParam|bundle)*>
<!ATTLIST scenarioPostProcessor class CDATA #REQUIRED>

<!ELEMENT errorHandler (initParam|bundle)*>
<!ATTLIST errorHandler class CDATA #REQUIRED>

<!ELEMENT pagePreProcessor (initParam|bundle)*>
<!ATTLIST pagePreProcessor class CDATA #REQUIRED>

<!ELEMENT pagePostProcessor (initParam|bundle)*>
<!ATTLIST pagePostProcessor class CDATA #REQUIRED>

<!ELEMENT pageExecutor (initParam|bundle)*>
<!ATTLIST pageExecutor class CDATA #REQUIRED>

<!ELEMENT segmentEexecutor (initParam|bundle)*>
<!ATTLIST segmentEexecutor class CDATA #REQUIRED>

<!ELEMENT initParam (#PCDATA)>
<!ATTLIST initParam name  CDATA #REQUIRED
                    value CDATA #IMPLIED>

<!ELEMENT bundle EMPTY>
<!ATTLIST bundle name CDATA #REQUIRED>

=== kirikprotocol/MSAG-Console/config/templates/MCIProf/schema/schema.xml
<?xml version="1.0" encoding="windows-1251"?>
<!DOCTYPE scenarios SYSTEM "file:///scenarios.dtd">
<scenarios>
  <scenario id="0" active="1" sms="1" ussd="2" resources="resources.xml">

    <page id="MAIN_PAGE" question="0">
      <segment>
        <data>
Ваши настройки:
1> Переадресация
2> Изм. переадресацию
3> Профиль
4> Изм. профиль
        </data>
      </segment>
      <command name="1" target="divert_info"/>
      <command name="2" target="divert_mgr"/>
      <command name="3" target="profile_info"/>
      <command name="4" target="profile_mgr"/>
      <command name="(**)" target="MAIN_PAGE"/>
    </page>

    <page id="divert_info" question="0">
      <pageExecutor class="ru.sibinco.mci.profile.DivertViewExecutor">
        <bundle name="divert"/>
      </pageExecutor>
      <command name="(**)" target="MAIN_PAGE"/>
    </page>
    <page id="divert_mgr" question="0">
      <segment>
        <data>
Установить переадресацию:
1> Занято
2> Отсутствует
3> Не доступен
4> Безусловно
        </data>
      </segment>
      <command name="1" target="divert_prompt"/>
      <command name="2" target="divert_prompt"/>
      <command name="3" target="divert_prompt"/>
      <command name="4" target="divert_prompt"/>
      <command name="(**)" target="MAIN_PAGE"/>
    </page>
    <page id="divert_prompt" question="0" >
      <pagePreProcessor class="ru.sibinco.mci.profile.DivertPromptPreprocessor"/>
      <segment>
        <data>
Введите номер телефона или
1> Выключить
2> Миссед Колс
3> Автоответчик
4> Назад
        </data>
      </segment>
      <command name="1" target="divert_set"/>
      <command name="2" target="divert_set"/>
      <command name="3" target="divert_set"/>
      <command name="4" target="diver_mgr"/>
      <command name="(**)" target="divert_set"/>
    </page>
    <page id="divert_set" question="0">
      <pageExecutor class="ru.sibinco.mci.profile.DivertSetExecutor">
        <bundle name="divert"/>
      </pageExecutor>
      <command name="(**)" target="divert_mgr"/>
    </page>


    <page id="profile_info" question="0">
      <!-- Lokup & show info only (depends on user's profile) -->
      <pageExecutor class="ru.sibinco.mci.profile.ProfileViewExecutor">
        <bundle name="profile"/>
      </pageExecutor>
      <command name="(**)" target="MAIN_PAGE"/>
    </page>
    <page id="profile_mgr" question="0">
      <!-- Lokup profile & show prepared menu with alternatives -->
      <pageExecutor class="ru.sibinco.mci.profile.ProfileChangeExecutor">
        <bundle name="profile"/>
      </pageExecutor>
      <command name="1" target="profile_flags"/>    <!-- change inform flag -->
      <command name="2" target="profile_flags"/>    <!-- change notify flag -->
      <command name="3" target="profile_messages"/> <!-- change inform message format -->
      <command name="4" target="profile_messages"/> <!-- change notify message format -->
      <command name="(**)" target="MAIN_PAGE"/>
    </page>
    <page id="profile_flags" question="0">
      <!-- Set inform/notify option -->
      <pagePreProcessor class="ru.sibinco.mci.profile.ProfileChangePreprocessor"/>
      <!-- Get inform/notify option & switch profile flag -->
      <pageExecutor class="ru.sibinco.mci.profile.ProfileChangeFlagsExecutor">
        <bundle name="profile"/>
      </pageExecutor>
      <command name="(**)" target="profile_mgr"/>
    </page>
    <page id="profile_messages" question="0">
      <!-- Set inform/notify option -->
      <pagePreProcessor class="ru.sibinco.mci.profile.ProfileChangePreprocessor"/>
      <!-- Get inform/notify option & show the set of profile message formats -->
      <pageExecutor class="ru.sibinco.mci.profile.ProfileMessagesExecutor">
        <bundle name="profile"/>
      </pageExecutor>
      <command name="0"    target="profile_mgr"/>
      <command name="(**)" target="profile_messages_change"/>
    </page>
    <page id="profile_messages_change" question="0">
      <!-- Get inform/notify option & show selected profile message format -->
      <pageExecutor class="ru.sibinco.mci.profile.ProfileChangeMessagesExecutor">
        <bundle name="profile"/>
      </pageExecutor>
      <command name="(**)" target="profile_mgr"/>
    </page>
    
  </scenario>
</scenarios>
